version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install deps
          command: ./s/install
      - run:
          name: lint
          command: ./s/lint

workflows:
  version: 2
  test:
    jobs:
      - lint
